name: PRs to master
on: 
  pull_request:
    branches: [release*]
    types: [closed]
jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git checkout master
          git pull
          git merge --no-ff ${{ steps.extract_branch.outputs.branch }} -m "Auto-merge master back to dev"
          git push
