name: test different options

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "first string" 
      - run: echo "second run"
        
