name: build for PR

on: 
  workflow_dispatch:
  pull_request:
    branches: [master]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "building stage"
      - name: "testing named step"
        run: echo "this is named echo task" 
      - name: "this should fail definitely"
        run: test mest pest
        
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is PR test"
      - name: "failing part"
        run: echo mecho techo
      
