name: build for PR

env:
  BRANCH_NAME1: $(echo ${GITHUB_REF#refs/heads/} | tr / -)
  BRANCH_NAME2: ${{GITHUB_REF#refs/heads/}}
on: 
  workflow_dispatch:
    inputs:
      Environment: 
        description: "Environment"
        required: true
        default: 'test'
  pull_request:
    branches: [master]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "building stage"
      - name: "named step"
        run: echo "this is named echo task" 
      - name: "show github.event context"
        run: echo "${{github.event}}"
      - name: "show github.event_name param"
        run: echo "${{github.event_name}}"
      - name: "print if run manually"
        run: echo "This was run manually"
        if: github.event_name == 'workflow_dispatch'
      - name: "print current branch name"
        run: |
          echo "${{ env.BRANCH_NAME1 }}
          echo "${{ env.BRANCH_NAME2 }}


        
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is PR test"
      - name: "second"
        run: echo mecho techo
      - name: "Conditional doesn't work if it's master branch and input is test or develop"
        run: echo ===============conditional================
        if: contains(github.ref, 'master') || (github.event.inputs.Environment != 'test' && github.event.inputs.Environment != 'develop')
